sarcasticadmin/dotfiles

.gitignore, .gitmodules, bash/.bashrc, rbenv/.rbenv/default-gems, ruby/.gemrc
Rob's gotta use ruby to everyone watch out!
=> Add rbenv to my dotfiles

.gitmodules, bash/.bashrc, vim/.vimrc
Need a simple golang dev environment
=> Golang initial

vim/.vim/spell/tech.utf-8.add
=> adding vpc bruh

git/.gitconfig
Now I can leverage side-by-side diffs in `icdiff` in git:
```
git difftool
/tmp/LVKtOM_.gitconfig                                                                                              git/.gitconfig                                                                                                     
4 [core]                                                                                                            4 [core]                                                                                                    
5   editor = vim                                                                                                    5   editor = vim                                                                                            
6   pager  = less -R …
```
=> [READY] Adding difftool to gitconfig

.gitignore, bash/.bashrc.d/11-vagrant, workstation-osx/.brewfile
Adding some `vagrant` env variables, `icdiff` to osx and ignoring my hub config for `git`
=> [READY] Misc dotfile configs

.circleci/config.yml, bash/.bashrc.d/10-golang, bash/.bashrc.d/10-hub, bash/.bashrc.d/10-python, bash/.bashrc.d/10-ruby, bash/.bashrc.d/11-cloud, bash/.bashrc.d/11-openssl, bash/.bashrc.d/11-osx, bash/.bashrc.d/11-vagrant
Helping me remember the mappings between AWS region names and codes
=> Adding 11-cloud to bashrc.d

bash/.bashrc
make sure `umask` is at least set to 0022 and some fun bash history stuff from https://sanctum.geek.nz/arabesque/better-bash-history/
=> [READY] Set umask and bash history tuning

bash/.bashrc.d/10-ag, bash/.bashrc.d/10-docker, docker/.docker.d/config.json, docs/APT.md, docs/DOCKER.md, docs/README.md
Adding configuration for docker formatting, agr, and misc docs
=> [READY] Adding docker alias sanity and other changes

bash/.bashrc, docs/PODCASTS.md, docs/README.md, docs/WORKSTATION-OSX.md, workstation-osx/bin/disable-updates.sh
* Stop osx update framework from prompting me every day
* Shorten PS1 prompt
* Podcast notes in `docs`
=> [READY] Disable osx updates

newsboat-osx/.newsboat/config, newsboat-osx/.newsboat/urls, newsboat/.newsboat/config, newsboat/.newsboat/urls
Newsboat needed a few updates for highlighting the dtrace blog and adding another comic
=> [READY] Adding nb highlighting and additional comic

docs/PYENV.md, docs/RBENV.md, laptop/bin/wifi, vim/.vim/spell/tech.utf-8.add
* Needed to get the lastest versions of python via pyenv
* Needed to get the lastest versions of ruby via rbenv
* `wifi` command for laptop needed some help
* Added some related docs
=> Update pyenv and rbenv submodules and wifi tool

git/.gitconfig
Adding `git stale` command to identify branches that have already been merged into the default (master) branch
=> [READY] - Adding git stale subcommand

bash/.bashrc.d/11-browser, linopen/.linopenrc, make/workstation-pkgs.mk, newsboat-osx/.newsboat/config, newsboat/.newsboat/config
* Adding more knobs to the `newsboat`
* rc file for linopen: https://github.com/sarcasticadmin/linopen
* `BROWSER` env variable on linux
=> [READY] Adding newsboat thread configs and BROWSER env

docs/WORKSTATION-OSX.md, workstation-osx/.brewfile
Adding docs around removing that annoying "Are you sure you want to open" for casks that are installed. Additionally adding ghostscript for `ps2pdf` binary.
=> [READY] - Adding Quarantine OSX docs

bash/.bashrc.d/10-python, docs/PIPX.md, docs/README.md
Adding `pipx` to path configurations. Will live alongside `pipsi` for the time being.
=> [READY] - Adding pipx bin config and docs

bash/.bashrc.d/11-cloud, docs/WORKSTATION-OSX.md, workstation-osx/.brewfile, workstation-osx/bin/osx-prefs.sh
* Bumping vim tf plugin to 0.12
* Adding some osx-workstation attribute configs
* Adding `aws-ec2-fp` for 11-cloud
=> [READY] Bump vim tf plugin to support 0.12 and misc

.gitignore, bash/.bashrc, bash/.bashrc.d/11-math, docs/HAM.md, docs/README.md, tmux/.tmux.conf
* Adding `bash` math functions
* Ham notes
* Bump `tmux` history
* Adding MANPAGER to `bashrc`
=> [READY] Adding ham notes and some new bash configs

docs/HAM.md, docs/KERMIT.md, docs/README.md, docs/SERIAL.md, kermit/.kermit/kantronics-3plus.kermit
* Adding kermit configs so enable documenting device `baud` and serial settings
* Packet radio ref
* Kantronics 3 + manual ref
=> [READY] adding kermit config

kermit/.kermit/pcengines-apu4.kermit, weechat/.weechat/irc.conf
* Adding new irc channels: nixos, freebsd
* Adding pcengines kermit config
=> [READY] Adding irc nixos and freebsd

.gitmodules, bash/.bashrc, bash/.bashrc.d/11-nix, vim/.vimrc
* `nix` colors for vim
* Load `nix` profile if it exists on system
* `diff` options unified and case insensitive search globally set
=> [READY] - Adding vim-nix plugin and diff options

docs/PKGNG.md, laptop/bin/wifi
Adding old notes and wifi mask
=> [READY] - Adding pkg notes and wifi mask pass

bash/.bashrc, tmux/.tmux.conf
See git log for specifics but trying to adding some new configs for tmux and less ANSI colors
=> [READY] Updates to tmux and less

bash/.bashrc
Some things around zeroing out the partition table via `nukepart` and adding a generic prompt
=> [READY] - Adding user-prompt and nukepart

bash/.bashrc.d/11-math, docs/JUNIPER.md, docs/README.md, git/.gitconfig
Long needed `git aliases` and `epoch` bash alias. Also some docs on the juniper cli since I cant remember what I need when Im in there
=> [READY] - Adding git aliases and epoch

.gitignore, bash/.bashrc.d/11-sys, docs/HAM.md, vim/.vimrc
HAM notes and `autofmt` changes. `autofmt` seems like it might eventually replace other plugins Ive had historically. I also need to look into getting on the vimplug train. Embedding git submodules is getting long in the tooth
=> [READY] - Adding notes, bumping and config nix in autofmt vim 

mozilla/.mozilla/firefox/sa/user.js
Firefox configuration per user.js. Dont have a way of installing it due to some of the oddities of how profiles work in firefox but this is a good start.
- `cp` into active firefox profile and restart firefox
=> [READY] - Finally wrangling firefox with user.js

newsboat-osx/.newsboat/config, newsboat-osx/.newsboat/urls, newsboat/.newsboat/config, newsboat/.newsboat/urls
- Adding a new comic (thejenkins)
- Making newsboat act a little more to my liking
=> [READY] - Updates to newsboat feeds and config

Xmodmap/.Xmodmap, _make/workstation-pkgs.mk, bash/.bashrc.d/11-demo, tmux/.tmux.conf, vim/.vimrc
Recent updates for demos, vim utf-8 and disabling xmodmap
=> Update to bash aliases, vimrc and xmodmap

newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, vim/.vimrc
- Adding some vim status bar updates and column selection
- https for aws status page
=> [READY] - Updates to vimrc and aws status page rss

git/.gitconfig, gnupg/.gnupg/gpg-agent.conf, gnupg/.gnupg/scdaemon.conf
- Fix previously changed gpg-agent configs
- Keep scdaemon for troubleshooting but leave it commented out
- increase parallelization with cloc
- git diff rename limit increased
=> [READY] - Fixing gnupg, revert scdaemon and misc

bash/.bashrc, bash/.bashrc.d/11-cloud, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, vim/.vimrc
New collection of updates:
- vim abbrev
- bashrc fingerprint updates
- bashrc aws aliases
- newboat urls
=> [READY] - Adding vim abbrev, bashrc updates and newsboat urls

git/.gitconfig, vim/.vimrc
- Note about vim python feature
- New git advice ignore
- Duplicate vim abbrev
=> [READY] - Misc notes and new ignore for git advice

bash/.bashrc, git/.gitconfig
- gitconfig updates for handling merge conflicts with more context via diff3
- `git checkout-date` now supports suffix arg
- bash var `elevate` now exported so functions can find it
=> [READY] - gitconfig and bash elevate

Xdefaults/.Xdefaults, i3/.i3/config
- I understand Xdefaults much better than previously
- i3 workspaces improvements
=> [READY] - Update to Xdefaults and i3

bash/.bashrc.d/11-direnv, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
- `direnv` sourcing if present in my path
- newsboat updates for ham feeds
- newsboat misc filter changes for titles to existing feeds
=> [READY] - direnv sourcing and newsboat updates

newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, vim/.vimrc
- Moving from all existing plugins to ALE due to syntastic deprecation notice
- Worked on the bulk of the languages in current development
=> [READY] - ALE for vim as solo plugin

newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
Adding sysops feeds to rss reader so that I have updates related to news and outages for winlink gateways
=> [READY] - Add winlink sysops feed to rss

GNUmakefile, Makefile, _make/workstation-pkgs.mk, gh/.config/gh/config.yml, vim/.vim/spell/tech.utf-8.add
- Finally having more support for `XDG_CONFIG_HOME`
- gh config simple but useful
- misc words being add to my dictionary
=> [READY] - XDG_CONFIG_HOME and gh config

bash/.bashrc.d/11-colors, bash/.bashrc.d/11-demo, i3/.i3/config, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, workstation/.i3status.conf
- Adding clear to demo and udemo funcs
- Fixing scrots screenshot artifacts
- init stripcolors bash alias
- adding rss feeds for diy599 and aprs
- update i3status for workstations
=> [READY] - updates for i3status, rss, i3 scrot, demo

i3/.i3/config, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, tmux/.tmux.conf, vim/.vimrc
- fixing i3 conflict of ws5 and percent
- enable tmux splitting via pipe
- turn off default ale linting behaviors
- init oxide and drew devault rss feeds
=> [READY] - i3, tmux, vim ale plugin and new rss feeds

git/.gitconfig, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
- enable git auto upstreaming
- remove lifehacker noise from rss feeds
=> [READY] - git remote branch tracker defaults and rm lifehacker rss

bash/.bashrc, git/.gitconfig, i3/.i3/i3lock.sh
- init zdiff3 for git merge conflicts
- ensure that gpg-agent exists for bashrc configs
- add comment for DPMS definition
=> [READY] - zdiff3 git diff and gpg-agent check

bash/.bashrc, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
- bash tab completion prefs
- init stacker news rss feed
- init academic tech research rss feeds
=> [READY] - bash completion preferences and rss feeds

laptop/bin/wifi
During con had to be able to target specific interfaces for wpa supplicant. Decided to pass through any extra flags to wpa_cli
- Tested on driver
=> [READY] - wifi: support flag passthrough for wpa_cli

git/.gitconfig, newsboat/.newsboat/urls, vim/.vim/spell/tech.utf-8.add, vim/.vimrc
- init git alias semver
- add loopback to spell dict
- move vim linter to flake8 and remove global black
- updates to ham rss feeds
- Working on `driver`
=> [READY] - semver git alias, vim flake8 linting, misc

vim/.vimrc
Set `ruler` in lower right corner for line and column numbers
=> [READY] vim: setting ruler

git/.gitconfig, vim/.vimrc
- vim: resume place in file
- git: commit --fixup to set f in rebase
=> [READY] - gitconfig autosquash and vim resume

alacritty/.config/alacritty/alacritty.yml, i3/.i3/config, i3/.i3/i3lock.sh, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, tmux/.tmux.conf
- alacritty: init
- i3: silence scrot bell
- i3: default to alacritty for term launch
- tmux: default to xsel for yanking to clipboard
- newsboat: init sfconservancy
- newsboat: dup osx urls updates
Tested on `driver`
=> [READY] - alacritty, newsboat

bash/.bashrc.d/11-openssh, git/.gitconfig, i3/.i3/config
- ssh-purge: init alias for ssh-keygen -R
- gitconfig: remove git checkout-prev
- i3: silence scrot during screenshot
=> [READY] - ssh-purge, i3 screenshot silence, and git config

bash/.bashrc.d/11-math, git/.gitconfig, i3/.i3/config
- git: testing rerere
- bashrc: init epoch2h
- i3: i3status default config pref
- Tested on `oddball`
=> [READY] - i3status, git rerere, epoch2h

tmux/bin/gotmux, vim/.vimrc
- tmux: check if ticker available for stocks window
- vim: forget last position for git* filetypes
- Tested working well on `driver`
=> [READY] - ticker in gotmux and position ignored for git fts

git/.gitconfig, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
gitconfig changes that were prompted by: https://jvns.ca/blog/2024/02/16/popular-git-config-options
- Confirmed working on `driver`
=> [READY] - gitconfig and newsboat updates

newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls, tmux/.tmux.conf
Ran into a odd bug with remote vim reenabling mouse support even after `set mouse-=a` turned out to be tmux mouse support mucking with functionality
Additionally, got a new comic thanks to Snug member: Mica
=> [READY] - tmux and newsboard comic

bin/bin/nosaver.sh, gnureadline/.inputrc, npm/.npmrc
- npm: init .npmrc
- bin: no screensaver X script
- inputrc: ensure history is intact even upon edits
- verified working on `driver`
=> [READY] - inputrc, npmrc, and nosaver.sh

bin/bin/nosaver.sh, newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
Bulk addition for ham radio newletters and blogs. And apparently I broke the CI with a missing shebang.
- Working on `driver`
=> [READY] - ham radio newsletters

newsboat-osx/.newsboat/urls, newsboat/.newsboat/urls
Found a lot of broken links in my feeds. These should now all be up to date
- Ensured they showed up in `newsboat`
- TBD add a url tester for these as part of CI
=> [READY] - newsboat: fix deadlines for existing feeds

newsboat/.newsboat/config, newsboat/.newsboat/filters/atom-rm-published-tag.sh, newsboat/.newsboat/urls
- **newsboat: init birkenhack feed**
- **newsboat: rm nixpkgs.news**
- **newsboat: init daily.hamweekly feed**
- **newsboat: set download timeout 30->10 sec**
=> newsboat: feed and config updates

newsboat/.newsboat/urls
- **newsboat: init datadog status feeds**
- **newsboat: init With Varying Frequency K9ZW**
=> newsboat: datadog and K9ZW feeds
