sarcasticadmin/dotfiles

- vim/.vimrc
because I can never remember how to re-enable spaces when I need to work with scale *.tsv. Thanks @owendelong
> Adding tsv ft to vimrc

- aws/.aws/cli/alias
Makes it easier to see tags on ec2 instances with my `aws running-instances` alias
> [READY] Change tag output for running-instances in aws aliases

- .gitmodules
- README.md
- bash/.bashrc
- bash/.bashrc.d/10-ag
- bash/.bashrc.d/10-docker
- bash/.bashrc.d/10-golang
- bash/.bashrc.d/10-hub
- bash/.bashrc.d/10-python
- bash/.bashrc.d/10-ruby
- bash/.bashrc.d/11-cloud
- bash/.bashrc.d/11-openssl
- bash/.bashrc.d/11-osx
- bash/.bashrc.d/11-vagrant
- docs/APT.md
- docs/BHYVE.md
- docs/PODCASTS.md
- docs/PORTS.md
- docs/README.md
- docs/SERIAL.md
- vim/.vim/spell/tech.utf-8.add
- vim/.vimrc
Needed some small helper functions for `awscli` and added `autoformat` for `rego` then included it for `autopep8` instead of the dedicated `autopep8` plugin
* Validated `aws` functions work as intended
* Validated `autoformat` plugin works as expected with `rego`, `sh` and `python`
> [READY] Adding aws env specifics and autofmt

- tmux-pre2.9/.tmux.conf
- tmux/.tmux.conf
Not ideal but need to finally support tmux 2.9+ config changes and will leave the legacy pre 2.9 config in the repo for scenarios where a older version of tmux is present.
> Support tmux 2.9+ and retain legacy tmux config

- bash/.bashrc.d/11-hashicorp
- bash/.bashrc.d/11-nix
nix-sha alias to leverage some of the sha generation when working on nixpkgs. And globally disable checkpoint env var since I dont want to have applications comment about updates when required to use older versions.
> Adding nix-sha and disable checkpoint env var

- git/.gitconfig
- gnureadline/.inputrc
- make/default-pkgs.mk
- make/workstation-pkgs.mk
See commit message for more details, but git config via normal 99 convention and GNUreadline config to stop 🔔 .
Confirmed working:
```
$ ls -lah ~/.inputrc
lrwxrwxrwx 1 rherna rherna 29 Dec  3 12:40 /home/rherna/.inputrc -> dotfiles/gnureadline/.inputrc
```
> [READY] Adding git config work include and GNUreadline config

- tmux/.tmux.conf
Finally came up with a compromise with myself: split panes will use $PWD while new windows will use $HOME in tmux 🎉
> Adding tmux split pane keep $PWD

- .gitignore
- vim/.vimrc
Move .swp and .undo out of `cwd` and into `~/.vim/.tmp`
> [READY] - Vim .swp and .undo

- _bootstrap/robs-prep-ubuntu.sh
- bash/.bashrc
Ubuntu makes fun "suggestions" that just get old after awhile:
```
$ ehco "hello"                                                                                                                                                             
Command 'ehco' not found, did you mean:
command 'echo' from deb coreutils (8.30-3ubuntu2)
Try: sudo apt install <deb name>
```
Also ran into a throttling problem with `ondemand` CPU scheduling
> [READY] - Disable ondemand CPU service and command not found

- .gitignore
- GNUmakefile
- Makefile
- bin/bin/wmi.sh
- vim/.vimrc
Follow up from: https://github.com/sarcasticadmin/dotfiles/pull/54
- autoformat was missing after vim-plug migration
- Updating `wmi.sh` since previous url was broken
- Adding `vim-plug-clean` if/when uninstalling vim plug plugins
> [READY] - Autoformat vim plugin missing and housekeeping

- bash/.bashrc.d/10-docker
- vim/.vimrc
- Cant ever remember how to get a container's ip with docker: `docker-ip`
- Finally able to toggle autoformat, although I wish it could be better since Im manipulating the entire write buffer
> [READY] - Toggle autoformat and init docker-ip alias

- bash/.bashrc.d/10-gh
- bash/.bashrc.d/11-cloud
- vim/.vimrc
- init gh bashrc aliases
- disable default pager for awscli
- Remove vim-plug for terraform
- Confirmed that tf works as expected with tf vim plugin removed
> [READY] - Remove tf vim plugin, gh aliases, disable awscli pager

- bash/.bashrc.d/11-colors
- i3/.i3/config
- vim/.vimrc
- rename bash fun from stripcolors -> nocolor
- Revert "enable i3 workspace quick return"
- init python lint and format via ale
- Confirmed `pylint` and `black` on development environment
- i3 quick return no longer enabled
> [READY] - nocolor, revert i3 prev workspace, and python pref

- git/.gitconfig
- newsboat-osx/.newsboat/config
- newsboat-osx/.newsboat/urls
- newsboat/.newsboat/config
- newsboat/.newsboat/urls
- disable git-lfs lock verification
- set default remote during git clone to upstream
- dilbert rss feed is no more
- init work chronicles comic feed
- init KB6NU ham feed
- highlight individuals rss feed in yellow
> [READY] - gitconfig remotes and rss feed update

- vim/.vimrc
For some terminal emulators that want to manipulate the cursor, explicitly set it for vim.
Behaves the same on:
- `windows powershell` -> `openSSH` -> `linux box` (containing vim config)
- `uxterm` on `NixOS`
> [READY] vim: xterm* for cursor type

- bash/.bashrc
To save my sanity from yet another kind of system bell.
Tested on sidekick (where the bell was originally noticed during a `git log`)
> [READY] bash: set less global env to -Q to silence bell

- bash/.bashrc
- i3/.i3/config
- newsboat-osx/.newsboat/urls
- newsboat/.newsboat/urls
- newsboat: missing status tag for gitlab
- bash: remove env path from MANPAGER
- i3: include alacritty in startup
* Tested on `driver`
> [READY] - MANPAGER update and i3 autostart alacritty

- i3/.i3/config
- i3/.xinitrc
- newsboat-osx/.newsboat/config
- newsboat-osx/.newsboat/urls
- newsboat/.newsboat/config
- newsboat/.newsboat/urls
Xmodmap wasnt loading so I wasnt able to effectively use my `insert key = ""` mapping. I finally figured out how to get newboat to load its cache for query aggregated lists.
- `driver` working as expected
> [READY] - newboat query cache and Xmodmap load

- vim/.vimrc
Looks like I broke `vimplug` when I merged https://github.com/sarcasticadmin/dotfiles/pull/107 This should fix it
- Tested on the mac
> [READY] vim: refer to correct plug dir

- git/.gitconfig
- newsboat/.newsboat/urls
Finally fixed the `git pat` subcommand for generating patches for things like nixpkgs.
CF seems to be something I'm using more these days, so adding theres status rss feed.
- working on `driver`
> [READY] - git pat and cloudflare feed

- git/.gitconfig
Take advantage of the blame ignore file and its default path in git repos if one exists
- Verified on the scale-network repo
> [READY] - git: add blame rev ignore

- newsboat/.newsboat/urls
- vim/.vimrc
Keep a closer eye on liminix since it might be a viable option for scale openwrt
Remove lint of tf since it leads to annoying errors regarding tf init and provider discovery
- Tested on macos
> [READY] - vim tf lint disable and liminix rss feed

- alacritty/.config/alacritty/alacritty.toml
- bash/.bashrc.d/10-glab
- git/.gitconfig
- newsboat/.newsboat/urls
- tmux/.tmux.conf
- vim/.vimrc
- enabled stacked branches during git rebase: https://andrewlock.net/working-with-stacked-branches-in-git-is-easier-with-update-refs/
- During the nixos 24.11 update - There we a few small changes to alacritty and tmux were required
- Confirmed working on `driver`
> [READY] - git, tmux, alacritty config updates

- k9s/.config/k9s/config.yaml
Needed the inverse for the to skip version checking
- Tested locally on MacOS
> k9s: skip version check and logo

- newsboat/.newsboat/config
Tired of always hitting ESC then q to leave newsboat article
- Verified working on macOS
> newsboat: ESC is q too
